CREATE TABLE IF NOT EXISTS IPV4_DATA (
  IP_FROM INTEGER,
  IP_TO INTEGER,
  REGISTRY VARCHAR(255),
  ASSIGNED INTEGER,
  CTRY VARCHAR(255),
  CNTRY VARCHAR(255),
  COUNTRY VARCHAR(512),
  REPORTED_AT VARCHAR(255)
);
