SELECT USER_IP_ADDRESS.USER_ID,
       IPV4_DATA.COUNTRY,
       IPV4_DATA.REPORTED_AT
FROM USER_IP_ADDRESS
LEFT JOIN IPV4_DATA ON USER_IP_ADDRESS.NUMERIC_IP BETWEEN IPV4_DATA.IP_FROM AND IPV4_DATA.IP_TO
WHERE IPV4_DATA.REPORTED_AT = '{reported_at}';
