WITH UNIQUE_USERS_BY_COUNTRY AS
  ( SELECT COUNT (DISTINCT USER_ID) AS UNIQUE_USERS,
                 COUNTRY
   FROM USER_COUNTRY_MAPPING
   WHERE REPORTED_AT = '{reported_at}'
   GROUP BY COUNTRY
   ORDER BY UNIQUE_USERS DESC),
     TOP_10_COUNTRIES AS
  ( SELECT COUNTRY
   FROM UNIQUE_USERS_BY_COUNTRY
   LIMIT 10)
SELECT CASE
           WHEN COUNTRY IN TOP_10_COUNTRIES THEN COUNTRY
           ELSE "Others"
       END AS COUNTRY,
       COUNT (DISTINCT USER_ID) AS UNIQUE_USERS
FROM USER_COUNTRY_MAPPING
WHERE REPORTED_AT = '{reported_at}'
GROUP BY CASE
             WHEN COUNTRY IN TOP_10_COUNTRIES THEN COUNTRY
             ELSE "Others"
         END
ORDER BY UNIQUE_USERS DESC;
